### ISSUE TITLE
Use with IE11

### ISSUE THREAD

**Issue by dgrant85** [Andarist/use-smooth-scroll#2]
I've been trying to use this in a project targeting IE11 however, as callbag is not ES5 compliant, i've been running into issues.

I've attempted modifying my webpack to exclude callbag modules but that doesn't seem to have worked e.g.

`loader: 'babel-loader',
        exclude: /node_modules\/(?!(are-passive-events-supported|callbag-duration-progress|callbag-flatten|callbag-from-event|callbag-map|callbag-merge|callbag-of|callbag-subject|callbag-subscribe|callbag-take-until|callbag-concat)\/).*/,`

Any recommendation on how I could use this in my project?

Thanks

**Comment by Andarist** [comment]
Well, it might depend on how your whole webpack config looks like. Try out this regexp first though:
```
/node_modules\/(?!callbag-.+)/
```

**Comment by dgrant85** [comment]
Thanks yes this was a wider issue with webpack config
